/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author siddharth
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productsBT = new javax.swing.JButton();
        customersBT = new javax.swing.JButton();
        suppliersBT = new javax.swing.JButton();
        transactionBT = new javax.swing.JButton();
        reportsBT = new javax.swing.JButton();
        WMBT = new javax.swing.JButton();
        SMBT = new javax.swing.JButton();
        CPBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Futura", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SG WAREHOUSE");

        jLabel2.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 84, 140));
        jLabel2.setText("Administrator Page");

        productsBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        productsBT.setForeground(new java.awt.Color(19, 115, 132));
        productsBT.setText("Products");
        productsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBTActionPerformed(evt);
            }
        });

        customersBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        customersBT.setForeground(new java.awt.Color(19, 115, 132));
        customersBT.setText("Customers");
        customersBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersBTActionPerformed(evt);
            }
        });

        suppliersBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        suppliersBT.setForeground(new java.awt.Color(19, 115, 132));
        suppliersBT.setText("Suppliers");
        suppliersBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersBTActionPerformed(evt);
            }
        });

        transactionBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        transactionBT.setForeground(new java.awt.Color(32, 93, 23));
        transactionBT.setText("Transactions");
        transactionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBTActionPerformed(evt);
            }
        });

        reportsBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        reportsBT.setForeground(new java.awt.Color(32, 93, 23));
        reportsBT.setText("Reports");
        reportsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBTActionPerformed(evt);
            }
        });

        WMBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        WMBT.setForeground(new java.awt.Color(37, 82, 173));
        WMBT.setText("Warehouse Managers");
        WMBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WMBTActionPerformed(evt);
            }
        });

        SMBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        SMBT.setForeground(new java.awt.Color(37, 82, 173));
        SMBT.setText("Sales Managers");
        SMBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMBTActionPerformed(evt);
            }
        });

        CPBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        CPBT.setForeground(new java.awt.Color(179, 173, 57));
        CPBT.setText("Change Password");
        CPBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPBTActionPerformed(evt);
            }
        });

        logoutBT.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        logoutBT.setForeground(new java.awt.Color(255, 0, 0));
        logoutBT.setText("LOGUT");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transactionBT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(productsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(suppliersBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SMBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CPBT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customersBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WMBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(suppliersBT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customersBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WMBT, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(transactionBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SMBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CPBT, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(logoutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(reportsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBTActionPerformed
        // TODO add your handling code here:
        dispose();
        TransactionPage objTraPage = new TransactionPage();
        objTraPage.setSize(875, 380);
        objTraPage.setVisible(true);
    }//GEN-LAST:event_transactionBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        dispose();
        login objlogPage = new login();
        objlogPage.setSize(875, 380);
        objlogPage.setVisible(true);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void productsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBTActionPerformed
        // TODO add your handling code here:
        dispose();
        ProductsPage objProPage = new ProductsPage();
        objProPage.setSize(875, 380);
        objProPage.setVisible(true);
    }//GEN-LAST:event_productsBTActionPerformed

    private void suppliersBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersBTActionPerformed
        // TODO add your handling code here:
        dispose();
        SuppliersPage objSupPage = new SuppliersPage();
        objSupPage.setSize(875, 380);
        objSupPage.setVisible(true);
    }//GEN-LAST:event_suppliersBTActionPerformed

    private void customersBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersBTActionPerformed
        // TODO add your handling code here:
        dispose();
        CustomersPage objCusPage = new CustomersPage();
        objCusPage.setSize(875, 380);
        objCusPage.setVisible(true);
    }//GEN-LAST:event_customersBTActionPerformed

    private void SMBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMBTActionPerformed
        // TODO add your handling code here:
        dispose();
        SalesManagerPage objSalesPage = new SalesManagerPage();
        objSalesPage.setSize(875, 380);
        objSalesPage.setVisible(true);
    }//GEN-LAST:event_SMBTActionPerformed

    private void WMBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WMBTActionPerformed
        // TODO add your handling code here:
        dispose();
        WarehouseManagerPage objWMPage = new WarehouseManagerPage();
        objWMPage.setSize(875, 380);
        objWMPage.setVisible(true);
    }//GEN-LAST:event_WMBTActionPerformed

    private void reportsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBTActionPerformed
        // TODO add your handling code here:
        dispose();
        ReportsPage objti = new ReportsPage();
        objti.setSize(875, 380);
        objti.setVisible(true);
    }//GEN-LAST:event_reportsBTActionPerformed

    private void CPBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPBTActionPerformed
        // TODO add your handling code here:
        dispose();
        adminPassChange objPPage = new adminPassChange();
        objPPage.setSize(875, 380);
        objPPage.setVisible(true);
    }//GEN-LAST:event_CPBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CPBT;
    private javax.swing.JButton SMBT;
    private javax.swing.JButton WMBT;
    private javax.swing.JButton customersBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton productsBT;
    private javax.swing.JButton reportsBT;
    private javax.swing.JButton suppliersBT;
    private javax.swing.JButton transactionBT;
    // End of variables declaration//GEN-END:variables
}
